name: 'Generate PDF from Markdown Files'
on: push

jobs:
  Generate_PDF:
      runs-on: ubuntu-latest
      steps:

      # This step is required
      - name: Clone Repo for MD to PDF
        uses: actions/checkout@v3


      - name: Convert MD to PDF
        uses: purplebearddan/ghAction-md2pdf@v1
      
      - name: Publish PDF to Sharepoint
        uses: purplebearddan/action-sharepoint-publish@v1.1.2
        with:
          site_url: ${{ vars.SITEURL }}
          library_folder: 'Shared Documents/Git Sync'
          sharepoint_client_id: ${{ secrets.SP_CLIENT_ID }}
          sharepoint_client_secret: ${{ secrets.SP_CLIENT_SECRET }}